files:
  - source: /src/locales/en_US/*.json
    translation: /src/locales/%locale_with_underscore%/%original_file_name%
  - source: /src/assets/help/en_US/*.md
    translation: /src/assets/help/%locale_with_underscore%/%original_file_name%
